In [103]:
# libraries
import numpy as np
import pandas as pd
from pydataset import data
import os
import matplotlib.pyplot as plt
import random
import seaborn as sns

In [104]:
print(random.random())

0.3853228881073525


In [105]:
random.randint(10,1000)

529

In [106]:
random.randrange(11, 35, 2)

21

In [107]:
my_list= ['apple', 'banana', 'cherry']
random.choice(my_list)

'banana'

In [108]:
my_list = [1, 2, 3, 4, 5, 6]
random.shuffle(my_list)
print(my_list)

[1, 3, 5, 6, 4, 2]


In [109]:
from scipy.stats import iqr
import numpy as np

In [110]:
import statistics as stats

In [111]:
x8 = [-100,10, 20, 30, 40, 50, 60, 70,1000] #vary this data
Q1 = np.percentile(x8, 25)
Q3 = np.percentile(x8, 75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = [x for x in x8 if x < lower_bound or x > upper_bound]
print(lower_bound, upper_bound,"Outliers:", outliers)

-40.0 120.0 Outliers: [-100, 1000]


In [112]:
random.sample(['apple','banana','cherry'],counts=[6,2,1],k=8)

['apple', 'apple', 'banana', 'banana', 'apple', 'apple', 'apple', 'apple']

In [113]:
random.sample(['apple','banana','cherry'],k=2)

['apple', 'banana']

In [114]:
random.choices(['apple','banana','cherry'], k=10)

['apple',
 'apple',
 'apple',
 'apple',
 'banana',
 'banana',
 'banana',
 'apple',
 'banana',
 'cherry']

In [115]:
df=data('mtcars')
df.head()

mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
Mazda RX4          21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
Mazda RX4 Wag      21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
Datsun 710         22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
Hornet 4 Drive     21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

                   carb  
Mazda RX4             4  
Mazda RX4 Wag         4  
Datsun 710            1  
Hornet 4 Drive        1  
Hornet Sportabout     2

In [116]:
df.dtypes

mpg     float64
cyl       int64
disp    float64
hp        int64
drat    float64
wt      float64
qsec    float64
vs        int64
am        int64
gear      int64
carb      int64
dtype: object

In [117]:
df.describe()

mpg        cyl        disp          hp       drat         wt  \
count  32.000000  32.000000   32.000000   32.000000  32.000000  32.000000   
mean   20.090625   6.187500  230.721875  146.687500   3.596563   3.217250   
std     6.026948   1.785922  123.938694   68.562868   0.534679   0.978457   
min    10.400000   4.000000   71.100000   52.000000   2.760000   1.513000   
25%    15.425000   4.000000  120.825000   96.500000   3.080000   2.581250   
50%    19.200000   6.000000  196.300000  123.000000   3.695000   3.325000   
75%    22.800000   8.000000  326.000000  180.000000   3.920000   3.610000   
max    33.900000   8.000000  472.000000  335.000000   4.930000   5.424000   

            qsec         vs         am       gear     carb  
count  32.000000  32.000000  32.000000  32.000000  32.0000  
mean   17.848750   0.437500   0.406250   3.687500   2.8125  
std     1.786943   0.504016   0.498991   0.737804   1.6152  
min    14.500000   0.000000   0.000000   3.000000   1.0000  
25%    16.892500   0.000000   0.000000   3.000000   2.0000  
50%    17.710000   0.000000   0.000000   4.000000   2.0000  
75%    18.900000   1.000000   1.000000   4.000000   4.0000  
max    22.900000   1.000000   1.000000   5.000000   8.0000

In [118]:
mpgvalues = df.mpg.sort_values().to_list() 
mpgvalues[0], mpgvalues[8], mpgvalues[16] , mpgvalues[24], mpgvalues[31]  #16,24,32]]  #32 : min(0), max(32), 25% (32/4=8), 50%(16), 75%(24)

(10.4, 15.5, 19.2, 22.8, 33.9)

In [119]:
df.mean(axis=0)

mpg      20.090625
cyl       6.187500
disp    230.721875
hp      146.687500
drat      3.596563
wt        3.217250
qsec     17.848750
vs        0.437500
am        0.406250
gear      3.687500
carb      2.812500
dtype: float64

In [120]:
df.mean(axis=1).head()

Mazda RX4            29.907273
Mazda RX4 Wag        29.981364
Datsun 710           23.598182
Hornet 4 Drive       38.739545
Hornet Sportabout    53.664545
dtype: float64

In [121]:
df.median(axis=0)  # axis=0 is default as well

mpg      19.200
cyl       6.000
disp    196.300
hp      123.000
drat      3.695
wt        3.325
qsec     17.710
vs        0.000
am        0.000
gear      4.000
carb      2.000
dtype: float64

In [122]:
x = [1,2,3,3,4,5]
x

[1, 2, 3, 3, 4, 5]

In [123]:
np.median(x)

np.float64(3.0)

In [124]:
random.shuffle(x)
x

[1, 2, 5, 3, 4, 3]

In [125]:
np.median(x)

np.float64(3.0)

# MODE - max freq

In [126]:

from scipy import stats

In [127]:
df.mode()

mpg  cyl   disp     hp  drat    wt   qsec   vs   am  gear  carb
0  10.4  8.0  275.8  110.0  3.07  3.44  17.02  0.0  0.0   3.0   2.0
1  15.2  NaN    NaN  175.0  3.92   NaN  18.90  NaN  NaN   NaN   4.0
2  19.2  NaN    NaN  180.0   NaN   NaN    NaN  NaN  NaN   NaN   NaN
3  21.0  NaN    NaN    NaN   NaN   NaN    NaN  NaN  NaN   NaN   NaN
4  21.4  NaN    NaN    NaN   NaN   NaN    NaN  NaN  NaN   NaN   NaN
5  22.8  NaN    NaN    NaN   NaN   NaN    NaN  NaN  NaN   NaN   NaN
6  30.4  NaN    NaN    NaN   NaN   NaN    NaN  NaN  NaN   NaN   NaN

In [128]:
df.gear.value_counts()

gear
3    15
4    12
5     5
Name: count, dtype: int64

In [129]:
df.carb.value_counts()

carb
4    10
2    10
1     7
3     3
6     1
8     1
Name: count, dtype: int64

In [130]:
df.cyl.mode()

0    8
Name: cyl, dtype: int64

In [131]:
df.cyl.value_counts()

cyl
8    14
4    11
6     7
Name: count, dtype: int64

In [132]:
import statistics as stats  #note same module in scipy
x1 = [1, 2, 2, 3, 4, 4, 4, 5,5,5,5]
x1

[1, 2, 2, 3, 4, 4, 4, 5, 5, 5, 5]

In [133]:
max(set(x1), key= x1.count)

5

In [134]:
max(set(x1))

5

In [135]:
print('Mode of list is ', stats.mode(x1))

Mode of list is  5


In [136]:
print('Multi Mode of list is ', stats.multimode(x1))

Multi Mode of list is  [5]


In [137]:
x2 = [1,1,2,2,3]
print(x2, ' : Multi Mode of list is ', stats.multimode(x2))

[1, 1, 2, 2, 3]  : Multi Mode of list is  [1, 2]


# Range

In [138]:
df[['mpg','wt']].max() - df[['mpg','wt']].min()

mpg    23.500
wt      3.911
dtype: float64

In [139]:
x3 = np.array([4, 8, 15, 16, 23, 42])
x3

array([ 4,  8, 15, 16, 23, 42])

In [140]:
np.ptp(x3)

np.int64(38)

In [141]:
df.apply(lambda col: col.max() - col.min())

mpg      23.500
cyl       4.000
disp    400.900
hp      283.000
drat      2.170
wt        3.911
qsec      8.400
vs        1.000
am        1.000
gear      2.000
carb      7.000
dtype: float64

In [142]:
x5 = [10, 20, 30, 40, 50, 60, 70]

# 25th, 50th (median), and 75th percentiles
q25 = np.quantile(x5, 0.25) #Q1
q50 = np.quantile(x5, 0.5) #Q2  , median
q75 = np.quantile(x5, 0.75) #Q3
print(q25, q50, q75)

25.0 40.0 55.0


In [143]:
import statistics as stats
stats.median(x5)      # 40
#stats.quantiles(x5, n=100)   # quartiles

40

In [144]:
df.describe()

mpg        cyl        disp          hp       drat         wt  \
count  32.000000  32.000000   32.000000   32.000000  32.000000  32.000000   
mean   20.090625   6.187500  230.721875  146.687500   3.596563   3.217250   
std     6.026948   1.785922  123.938694   68.562868   0.534679   0.978457   
min    10.400000   4.000000   71.100000   52.000000   2.760000   1.513000   
25%    15.425000   4.000000  120.825000   96.500000   3.080000   2.581250   
50%    19.200000   6.000000  196.300000  123.000000   3.695000   3.325000   
75%    22.800000   8.000000  326.000000  180.000000   3.920000   3.610000   
max    33.900000   8.000000  472.000000  335.000000   4.930000   5.424000   

            qsec         vs         am       gear     carb  
count  32.000000  32.000000  32.000000  32.000000  32.0000  
mean   17.848750   0.437500   0.406250   3.687500   2.8125  
std     1.786943   0.504016   0.498991   0.737804   1.6152  
min    14.500000   0.000000   0.000000   3.000000   1.0000  
25%    16.892500   0.000000   0.000000   3.000000   2.0000  
50%    17.710000   0.000000   0.000000   4.000000   2.0000  
75%    18.900000   1.000000   1.000000   4.000000   4.0000  
max    22.900000   1.000000   1.000000   5.000000   8.0000

In [145]:
df.describe(include='all').loc[['min','25%','50%','75%','max']]

mpg  cyl     disp     hp   drat       wt     qsec   vs   am  gear  \
min  10.400  4.0   71.100   52.0  2.760  1.51300  14.5000  0.0  0.0   3.0   
25%  15.425  4.0  120.825   96.5  3.080  2.58125  16.8925  0.0  0.0   3.0   
50%  19.200  6.0  196.300  123.0  3.695  3.32500  17.7100  0.0  0.0   4.0   
75%  22.800  8.0  326.000  180.0  3.920  3.61000  18.9000  1.0  1.0   4.0   
max  33.900  8.0  472.000  335.0  4.930  5.42400  22.9000  1.0  1.0   5.0   

     carb  
min   1.0  
25%   2.0  
50%   2.0  
75%   4.0  
max   8.0

# Percentile

In [146]:
from scipy import stats
import numpy as np

x6 = np.array([10, 20, 30, 40, 50, 60, 70])
x6

array([10, 20, 30, 40, 50, 60, 70])

In [147]:
q25, q50, q75 = np.percentile(x6, [25, 50, 75], method='linear')
print(q25, q50, q75)

25.0 40.0 55.0


In [148]:
np.quantile(x6, [0.25, 0.5, 0.75], method='midpoint')
#Different method options (e.g., 'linear', 'lower', 'higher', 'midpoint', 'nearest') 
#change how quantiles are interpolated.

array([25., 40., 55.])

# IQR
difference in Q3 & Q1

In [149]:
x7= [10, 20, 30, 40, 50, 60, 70]

Q1 = np.percentile(x7, 25)
Q3 = np.percentile(x7, 75)
IQR = Q3 - Q1

print(x7, "\n\n Q1:", Q1, " Q3:", Q3, " IQR:", IQR)

[10, 20, 30, 40, 50, 60, 70] 

 Q1: 25.0  Q3: 55.0  IQR: 30.0


In [150]:
from scipy.stats import iqr
import numpy as np

x7B = np.array([10, 20, 30, 40, 50, 60, 70])
IQR = iqr(x7B)
print(x7B, "\n IQR:", IQR)

[10 20 30 40 50 60 70] 
 IQR: 30.0


In [151]:
import statistics as stats
x7C = [10, 20, 30, 40, 50, 60, 70]
q = stats.quantiles(x7C, n=4)
IQR = q[2] - q[0]
print(x7C, "\n\n Q[2]", q[2], "Q[0]", q[0], ":: IQR:", IQR)

[10, 20, 30, 40, 50, 60, 70] 

 Q[2] 60.0 Q[0] 20.0 :: IQR: 40.0


# Outliers

In [152]:
x8 = [-150, -100,-90, -25, -5, -1, 10, 20, 30, 40, 50, 60, 70, 500, 1000] #vary this data
Q1 = np.percentile(x8, 25)
Q3 = np.percentile(x8, 75)
IQR = Q3 - Q1
Q2 = np.percentile(x8, 50)

lower_bound = Q1 - 1.5 * IQR  # <
upper_bound = Q3 + 1.5 * IQR  # >
print(Q1, Q2, Q3, IQR, lower_bound, upper_bound)
# values < lower_bound and values > upper_bound are oultiers

-15.0 20.0 55.0 70.0 -120.0 160.0


In [153]:
outliers = [x for x in x8 if x < lower_bound or x > upper_bound]
print("Outliers:", outliers)

Outliers: [-150, 500, 1000]


# Std Deviation/ Variance
Standard deviation is a statistical measure of data variability, indicating how spread out values are from their mean. A low standard deviation means data points are clustered near the mean, while a high standard deviation signifies data points are widely dispersed.
Use pvariance() / pstdev() for population data.
Use variance() / stdev() for sample data (divides by n-1).

In [154]:
x9 = [10, 20, 30, 40, 50]
print(x9)

[10, 20, 30, 40, 50]


In [155]:
np.std(x9), np.var(x9) #std is squareroot of var

(np.float64(14.142135623730951), np.float64(200.0))

In [156]:
# Population statistics
var_pop = stats.pvariance(x9)
std_pop = stats.pstdev(x9)
# Sample statistics
var_samp = stats.variance(x9)
std_samp = stats.stdev(x9)
print(" Data is ", x9)
print("Population Var:", var_pop, " Std:", std_pop)
print("Sample Var:", var_samp, " Std:", std_samp)

 Data is  [10, 20, 30, 40, 50]
Population Var: 200  Std: 14.142135623730951
Sample Var: 250  Std: 15.811388300841896


In [157]:
df.std()

mpg       6.026948
cyl       1.785922
disp    123.938694
hp       68.562868
drat      0.534679
wt        0.978457
qsec      1.786943
vs        0.504016
am        0.498991
gear      0.737804
carb      1.615200
dtype: float64

In [158]:
df.var()

mpg        36.324103
cyl         3.189516
disp    15360.799829
hp       4700.866935
drat        0.285881
wt          0.957379
qsec        3.193166
vs          0.254032
am          0.248992
gear        0.544355
carb        2.608871
dtype: float64